---
development:
  dialect: postgres
  database: sales_app_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@db:5432/sales_app_production?sslmode=disable"}}
