version: '3'
services:
  app:
    build: .
    container_name: sales_app
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sales_app_production
    ports:
      - '5432:5432'
