package actions

import (

  "fmt"
  "net/http"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop/v5"
  "github.com/gobuffalo/x/responder"
  "github.com/henry-jackson/challenges/sales_admin/sales_app/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Merchant)
// DB Table: Plural (merchants)
// Resource: Plural (Merchants)
// Path: Plural (/merchants)
// View Template Folder: Plural (/templates/merchants/)

// MerchantsResource is the resource for the Merchant model
type MerchantsResource struct{
  buffalo.Resource
}

// List gets all Merchants. This function is mapped to the path
// GET /merchants
func (v MerchantsResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  merchants := &models.Merchants{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Merchants from the DB
  if err := q.All(merchants); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // Add the paginator to the context so it can be used in the template.
    c.Set("pagination", q.Paginator)

    c.Set("merchants", merchants)
    return c.Render(http.StatusOK, r.HTML("/merchants/index.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(merchants))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(merchants))
  }).Respond(c)
}

// Show gets the data for one Merchant. This function is mapped to
// the path GET /merchants/{merchant_id}
func (v MerchantsResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Merchant
  merchant := &models.Merchant{}

  // To find the Merchant the parameter merchant_id is used.
  if err := tx.Find(merchant, c.Param("merchant_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    c.Set("merchant", merchant)

    return c.Render(http.StatusOK, r.HTML("/merchants/show.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(merchant))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(merchant))
  }).Respond(c)
}

// New renders the form for creating a new Merchant.
// This function is mapped to the path GET /merchants/new
func (v MerchantsResource) New(c buffalo.Context) error {
  c.Set("merchant", &models.Merchant{})

  return c.Render(http.StatusOK, r.HTML("/merchants/new.plush.html"))
}
// Create adds a Merchant to the DB. This function is mapped to the
// path POST /merchants
func (v MerchantsResource) Create(c buffalo.Context) error {
  // Allocate an empty Merchant
  merchant := &models.Merchant{}

  // Bind merchant to the html form elements
  if err := c.Bind(merchant); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(merchant)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the new.html template that the user can
      // correct the input.
      c.Set("merchant", merchant)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/merchants/new.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "merchant.created.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/merchants/%v", merchant.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.JSON(merchant))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.XML(merchant))
  }).Respond(c)
}

// Edit renders a edit form for a Merchant. This function is
// mapped to the path GET /merchants/{merchant_id}/edit
func (v MerchantsResource) Edit(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Merchant
  merchant := &models.Merchant{}

  if err := tx.Find(merchant, c.Param("merchant_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  c.Set("merchant", merchant)
  return c.Render(http.StatusOK, r.HTML("/merchants/edit.plush.html"))
}
// Update changes a Merchant in the DB. This function is mapped to
// the path PUT /merchants/{merchant_id}
func (v MerchantsResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Merchant
  merchant := &models.Merchant{}

  if err := tx.Find(merchant, c.Param("merchant_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  // Bind Merchant to the html form elements
  if err := c.Bind(merchant); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(merchant)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the edit.html template that the user can
      // correct the input.
      c.Set("merchant", merchant)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/merchants/edit.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "merchant.updated.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/merchants/%v", merchant.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(merchant))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(merchant))
  }).Respond(c)
}

// Destroy deletes a Merchant from the DB. This function is mapped
// to the path DELETE /merchants/{merchant_id}
func (v MerchantsResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Merchant
  merchant := &models.Merchant{}

  // To find the Merchant the parameter merchant_id is used.
  if err := tx.Find(merchant, c.Param("merchant_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  if err := tx.Destroy(merchant); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a flash message
    c.Flash().Add("success", T.Translate(c, "merchant.destroyed.success"))

    // Redirect to the index page
    return c.Redirect(http.StatusSeeOther, "/merchants")
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(merchant))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(merchant))
  }).Respond(c)
}
