version: '3'
services:
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: portal-admin
      POSTGRES_DB: portal
  
  ui:
    build: ./src/ui
    ports:
      - "4200:4200"
  
  api:
    build: ./src/api
    ports: 
      - "9090:9090"
    environment:
      DB_USER: portal-admin
      DB_PASS: password
      DB_NAME: portal
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_MAX_LIFETIME: 60
      DB_MAX_OPEN_CONNECTIONS: 50
      DB_MAX_IDLE_CONNECTIONS: 5
      DB_MAX_ATTEMPTS: 10
      APP_PORT: 4200
      APP_HOST: http://localhost
      API_PORT: 9090
      LOG_LEVEL: info
      ACCESS_CONTROL_ALLOW_ORIGINS: http://localhost:4200
      JWT_SECRET: ZPDDvgd2hnKJzV42cRUB7pmfpUxsXY
      ADMIN_USER: xenu@scientology.com
      ADMIN_PASSWORD: Sup3rKam!Xenu